apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    prometheus.io/port: "5000"
    prometheus.io/scrape: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }} 
      http:
        paths:
          - path: /?(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
