apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim-v2
  labels:
    app: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
